## 00.Pytorch Fundamentals


In [101]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [2]:
print("Hello, I'm excited to learn Pytorch!")

Hello, I'm excited to learn Pytorch!


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [102]:
import torch
torch.tensor(1)


tensor(1)

In [4]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor ([[7,8],
[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.0788, 0.7157, 0.5680, 0.6717, 0.3294, 0.3174, 0.3854, 0.9760, 0.2383,
         0.5919],
        [0.6742, 0.4615, 0.7435, 0.0406, 0.6330, 0.1721, 0.0499, 0.7968, 0.1525,
         0.4678],
        [0.1360, 0.1285, 0.5499, 0.1393, 0.1520, 0.9962, 0.8155, 0.5871, 0.2542,
         0.7065],
        [0.6306, 0.3720, 0.7542, 0.7740, 0.1851, 0.9306, 0.5133, 0.1343, 0.3535,
         0.0450],
        [0.9693, 0.9579, 0.9746, 0.3956, 0.1529, 0.4412, 0.9777, 0.6026, 0.1645,
         0.8421],
        [0.9500, 0.9767, 0.0728, 0.4967, 0.5303, 0.4565, 0.1544, 0.7454, 0.8923,
         0.9653],
        [0.8934, 0.3292, 0.2456, 0.7401, 0.9017, 0.0832, 0.1732, 0.8911, 0.4501,
         0.0535],
        [0.9920, 0.9802, 0.2183, 0.6158, 0.3883, 0.8689, 0.8031, 0.8708, 0.7207,
         0.7648],
        [0.0379, 0.0121, 0.7072, 0.9617, 0.7064, 0.0898, 0.1781, 0.3321, 0.1834,
         0.5376],
        [0.3356, 0.4435, 0.8635, 0.3425, 0.5440, 0.3444, 0.3510, 0.8312, 0.1493,
         0.1266]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(3,3)

tensor([[0.9069, 0.6883, 0.6336],
        [0.3470, 0.5024, 0.2341],
        [0.0945, 0.3270, 0.8396]])

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size =(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size =(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor attributes
1. Tensors not right datatype - to get datatype from a tensor - tensor.dtype
2. Tensor not right shape - to get shape from a tensor - tensor.shape
3. Tensor not right device - to get device from a tensor - tensor.device

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6699, 0.9940, 0.7152, 0.8723],
        [0.6786, 0.6729, 0.2336, 0.0702],
        [0.7577, 0.7957, 0.1182, 0.2889]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor in on: {some_tensor.device}")

tensor([[0.6699, 0.9940, 0.7152, 0.8723],
        [0.6786, 0.6729, 0.2336, 0.0702],
        [0.7577, 0.7957, 0.1182, 0.2889]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor in on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply it by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [37]:
tensor

tensor([10, 20, 30])

In [38]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [39]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [40]:
# Addition
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)
www.mathisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3, 2) @ (3, 2)' won't work  
* '(2, 3) @ (3, 2) will work
* '(3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimensions:
*'(2, 3) @ (3, 2)' -> '(2, 2)'
*'(3, 2) @ (2, 3)' -> '(3, 3)


www.matrixmultiplication.xyz


In [41]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [42]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [43]:
tensor

tensor([10, 20, 30])

In [44]:
# Matrix multiplication by hand


In [45]:
10*10+ 20 *20 + 30*30

1400

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.69 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 61 µs, sys: 10 µs, total: 71 µs
Wall time: 74.6 µs


tensor(1400)

In [48]:
tensor @ tensor

tensor(1400)

In [49]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4791, 1.1399],
        [0.8551, 1.5855]])

One of the most common errors in deep learning: shape errors

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [69]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [70]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [71]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A {tensor_A.shape } (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:


Output shape: torch.Size([3, 3])


In [54]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [53]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
# Finnd the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [57]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [58]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [59]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argim ()
x.argmin()

In [61]:
x[0]

tensor(1)

In [66]:
# Find the position in tensor that has the maximum value in argmax()
x.argmax()

tensor(7)

from types import WrapperDescriptorType
## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to a defined Shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 'l' dimensions from a tensor
* Unsqueeze - add a 'l' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [62]:
# Let's create a tensor
import torch
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [85]:
# Add an extra dimension
x_reshaped = x.reshape(1, 8)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [86]:
# Change the view
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [87]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [76]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [93]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])


In [96]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [98]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, colour_channels)

# Permute the original tensor to rearrange the axias (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [92]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [99]:
x_original [0, 0, 0] = 728218
x_original [0, 0, 0], x_permuted [0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [103]:
# Create a tensor
import torch
torch.tensor(1)
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [104]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [106]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [109]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [110]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [111]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [112]:
# Get all values of the 0 dimensions but only the 1 index 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [113]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [114]:
# Index on x to return 9
print(x[0][2][2])


tensor(9)


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computer torch.library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> 'torch.torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [124]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy´s default datatype of float64 unless otherwise specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [125]:
tensor.dtype

torch.float64

In [120]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [126]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [130]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...'

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is flavour the randomness.



In [135]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4878, 0.8308, 0.5266, 0.0442],
        [0.9467, 0.1775, 0.8934, 0.9482],
        [0.0346, 0.8841, 0.8458, 0.1749]])
tensor([[0.4817, 0.7208, 0.7908, 0.8683],
        [0.4932, 0.2929, 0.0689, 0.9504],
        [0.3660, 0.1892, 0.6504, 0.2132]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [138]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a bit of setup and requires investment
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up.

In [2]:
!nvidia-smi

Tue Dec 19 23:38:16 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
# Check for GPU access with PyTorch
import torch
torch.tensor(1)
torch.cuda.is_available()

True

For PyTorch since it´s capable of running compute on the GPU or CPU, it´s best practice to setup device agnostic code:
www.pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count the number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [12]:
# If tensor is on GPU, can't transform it to NumPy
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])